version: "2"
services:
    # user-service:
    #     depends_on: 
    #         - user-database
    #     container_name: user-service
    #     build: .
    #     ports:
    #         - "8082:8080"
        
    user-database:
        container_name: user-service
        image: postgres
        ports:
            - "5433:5432"
        environment: 
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
        volumes:
            - ./db_init/init.sh:/docker-entrypoint-initdb.d/init.sh